### ISSUE TITLE
Merge the branches

### ISSUE THREAD

**Issue by GoogleCodeExporter** [waliworld/geoxml3#52]
```
Given that it appears that poly is the main development trunk, the branches 
should probably be merged together into trunk.  If you think poly is stable 
enough, this could be set as a new release, and then a dev branch could be 
started from there.

As it is now, development might be a bit fractured with the multiple branches.  
Also, the current stable version is pretty old compared to what's already in 
poly.  (For example, the Overlay file is no longer required, etc.)

Besides, the code is small enough that stable releases could be made every few 
months.
```

Original issue reported on code.google.com by `sineswi...@gmail.com` on 8 Feb 2012 at 3:15

**Comment by waliworld** [comment]
Mr. Geocodezip is retarded, master branch is half way to worthless. (no poly support in master!?) This is so happening.

**Comment by waliworld** [comment]
kmz and wiki branch will be left alone (ill look into KMZ support later, i dont need it right now), old-master and network_link will be deleted out right. poly branch will be merged with master

**Comment by waliworld** [comment]
instead merging I just copied the polys branch codebase over to master. its sad to lose those commits but between that and resolving the merge conflicts, yeah... no.
